# Generated by Django 5.1.2 on 2024-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('seller', 'Vendedor')], default='seller', max_length=20),
        ),
    ]
