# Generated by Django 5.1.2 on 2024-11-04 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_options_remove_category_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número de venta')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('DEBIT', 'Tarjeta Débito'), ('CREDIT', 'Tarjeta Crédito')], max_length=10, verbose_name='Método de pago')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('CANCELLED', 'Anulada')], default='COMPLETED', max_length=10, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.IntegerField(verbose_name='Precio unitario')),
                ('purchase_price', models.IntegerField(verbose_name='Precio de compra')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('is_tax_included', models.BooleanField(default=True, verbose_name='Incluye IVA')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
    ]
