# Generated by Django 5.1.2 on 2024-11-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completada'), ('PENDING', 'Pendiente de Pago'), ('CANCELLED', 'Anulada')], default='COMPLETED', max_length=10, verbose_name='Estado'),
        ),
    ]
