# Generated by Django 5.1.2 on 2024-11-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_is_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='Modificada'),
        ),
    ]
