# Generated by Django 5.1.2 on 2024-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_purchase_with_tax',
            field=models.BooleanField(default=False, verbose_name='Precio de compra incluye IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_purchase_price',
            field=models.IntegerField(default=0, verbose_name='Precio de Compra Neto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='profit_percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje de Ganancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='Precio de Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Precio de Venta Final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_price',
            field=models.IntegerField(default=0, verbose_name='Precio Sugerido sin IVA'),
            preserve_default=False,
        ),
    ]
